stellingen:
  1 : 'investeringen in ov belangrijker dan autowegen'
  2 : 'overheid moet boeren helpen naar een kringlooplandbouw'
  3 : 'Nieuwe investeringen fossiel moeten we voorkomen'
  4 : 'er moet een wet komen die de uitstoot van  broeikasgassen verbiedt'
  5 : 'bedrijven moeten mee gaan betalen aan klimaatbeleid'
  6 : 'lage inkomens mogen er niet op achteruitgaan door de klimaat maatregelen'
  7 : 'klimaatschadelijk producten niet meer in de supermarkt '